version: '3'

services:
  api:   
    env_file:
        "./api/.env"  
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: "mrfritz/gz_tech:gz_api"
    ports:
      - "5000:5000" 
    depends_on:
      - postgres                     
    restart: on-failure
        
  app:    
    build: 
      context: ./app
      dockerfile: ./Dockerfile
    image: "mrfritz/gz_tech:gz_app"
    ports:
      - "3000:3000"
    links:
      - "api"

  postgres:
    image: postgres:14
    container_name: pg_container
    restart: always    
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bancogazin
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
